# Nome do workflow que vai aparecer no "Actions"
name: Pipeline CI/CD
run-name: ${{ github.actor }} is learning GitHub Actions
# Definir quando o Pipeline será disparado
on: 
  push:
    branches:
      - main
    paths: # só dispara se arquivos nessa pasta mudarem
      - "m27-testes-integracao-react-next/cinelista/**"
      - ".github/workflows/**" # mudanças nos próprios pipelines
  workflow_dispatch: # habilitar "run workflow" no GitHub Actions
  
jobs:
  # Primeiro job: build
  build:
    runs-on: ubuntu-latest #Imagem da máquina usada no CI
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v6
        
      - name: Instalação do Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Instalação das Dependências
        run: npm install
        working-directory: m27-testes-integracao-react-next/cinelista # executa o comando dentro da pasta

      - name: Rodar o Build
        run: npm run build
        working-directory: m27-testes-integracao-react-next/cinelista
        env: 
          TMDB_API_URL: ${{ vars.TMDB_API_URL }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          NEXT_PUBLIC_TMDB_API_IMG_URL: ${{ vars.NEXT_PUBLIC_TMDB_API_IMG_URL }}

  # Segundo job: tests
  tests:
    runs-on: ubuntu-latest #Imagem da máquina usada no CI
    needs: build
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v6
        
      - name: Instalação do Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Instalação das Dependências
        run: npm install
        working-directory: m27-testes-integracao-react-next/cinelista

      - name: Rodar lint
        run: npm run lint
        working-directory: m27-testes-integracao-react-next/cinelista

      - name: Verificar format
        run: npm run format -- --check
        working-directory: m27-testes-integracao-react-next/cinelista

      - name: Rodar testes
        run: npm run test
        working-directory: m27-testes-integracao-react-next/cinelista

  # Terceiro job: deploy
  deploy:
    runs-on: ubuntu-latest #Imagem da máquina usada no CI
    needs: tests
      
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v6
          
      - name: Instalação do Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
  
      - name: Instalação Vercel CLI
        run: npm install -g vercel@latest
  
      - name: Deploy para Vercel
        run: vercel 6-testes-qualidade-codigo/m27-testes-integracao-react-next/cinelista --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env: 
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
